config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "static_pages#index"

  get 'sobre', to: 'static_pages#sobre'
  get 'contato', to: 'static_pages#contato'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

    def index
    end

    def sobre
    end

    def contato
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <p class="lead">
      <%= link_to 'Contact List', root_path %>. Todos os direitos reservados.
    </p>
  </small>

  <ul class="nav justify-content-end">
    <li class="nav-item">
      <%= link_to 'Sobre', sobre_path, class:'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Contato', contato_path, class:'nav-link' %>
    </li>
  </ul>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to 'Contact List', root_url, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
  <!-- Conteudo exibido em telas maiores e que serao escondidos em telas menores -->
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
        <a class="nav-link" href="#">Cadastrar</a>
      </li>
      <li class="nav-item">
        <%= link_to 'Entrar', '#', class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/header' %>

    <div class="container mt-3">
      <% flash.each do |message_type, message| %>
        <%= content_tag 'div', class: "alert alert-#{message_type} alert-dismissible", role: 'alert' do %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= message %>
        <% end %>
      <% end %>
      
      <%= yield %>
      
      <%= render 'layouts/footer' %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  </body>
</html>

app/views/static_pages/contato.html.erb
<div class="card">
  <div class="card-body">
    <h2 class="card-title">Contato</h2>
    <p class="card-text">
      Entre em contato com <a href="http://www.twitter.com/brunojppb">@brunojppb</a> para saber mais.
    </p>
  </div>
</div>

app/views/static_pages/index.html.erb
<div class="card">
  <div class="card-body">
    <h2 class="card-title">Contact List</h2>
    <p class="card-text">
      Gerencie seus contatos em qualquer lugar!
    </p>
    <p>
      <a href="#" class="btn btn-primary">Crie sua conta!</a>
    </p>
  </div>
</div>

app/views/static_pages/sobre.html.erb
<div class="card">
  <div class="card-body">
    <h2 class="card-title">Sobre</h2>
    <p class="card-text">
      Criado com o intuito de ensinar um pouco sobre o Framework Ruby on Rails, Contact List mostrará como aprender as peças que formam essa ferramenta tão poderosa.
    </p>
  </div>
</div>